name: cookie_store
description: A RFC compliant cookie store
repository: https://github.com/foldland/cookie_store
issue_tracker: https://github.com/foldland/cookie_store/issues
version: 0.1.0
publish_to: none
topics:
  - http
  - cookies
  - rfc6265

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.0.0
  timezone: ^0.10.1

dev_dependencies:
  cookie_store_conformance_tests:
    git:
      url: https://github.com/foldland/cookie_store
      path: packages/cookie_store_conformance_tests
      tag_pattern: cookie_store_conformance_tests-v{{version}}
    version: ^0.1.0
  test: ^1.25.15
